export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];

export const LANGUAGE_TO_FLAG = {
  // European Languages
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  italian: "it",
  portuguese: "pt",
  russian: "ru",
  polish: "pl",
  dutch: "nl",
  greek: "gr",
  swedish: "se",
  norwegian: "no",
  danish: "dk",
  finnish: "fi",
  czech: "cz",
  hungarian: "hu",
  romanian: "ro",
  bulgarian: "bg",
  croatian: "hr",
  serbian: "rs",
  slovak: "sk",
  slovenian: "si",
  estonian: "ee",
  latvian: "lv",
  lithuanian: "lt",
  ukrainian: "ua",
  icelandic: "is",
  maltese: "mt",
  irish: "ie",
  welsh: "gb",
  
  // Asian Languages
  mandarin: "cn",
  cantonese: "hk",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  bengali: "bd",
  urdu: "pk",
  tamil: "in",
  telugu: "in",
  marathi: "in",
  gujarati: "in",
  kannada: "in",
  malayalam: "in",
  thai: "th",
  vietnamese: "vn",
  indonesian: "id",
  malay: "my",
  tagalog: "ph",
  burmese: "mm",
  khmer: "kh",
  lao: "la",
  
  // Middle Eastern Languages
  arabic: "sa",
  hebrew: "il",
  turkish: "tr",
  persian: "ir",
  farsi: "ir",
  pashto: "af",
  kurdish: "iq",
  
  // African Languages
  swahili: "ke",
  yoruba: "ng",
  igbo: "ng",
  amharic: "et",
  hausa: "ng",
  zulu: "za",
  xhosa: "za",
  somali: "so",
  luganda: "ug",
  sesotho: "ls",
  setswana: "bw",
  
  // American Languages
  english_us: "us",
  spanish_mx: "mx",
  portuguese_br: "br",
  french_ca: "ca",
  
  // Country Codes (for nationality)
  afghanistan: "af",
  albania: "al",
  algeria: "dz",
  andorra: "ad",
  angola: "ao",
  argentina: "ar",
  armenia: "am",
  australia: "au",
  austria: "at",
  azerbaijan: "az",
  bahamas: "bs",
  bahrain: "bh",
  bangladesh: "bd",
  barbados: "bb",
  belarus: "by",
  belgium: "be",
  belize: "bz",
  benin: "bj",
  bhutan: "bt",
  bolivia: "bo",
  bosnia: "ba",
  botswana: "bw",
  brazil: "br",
  brunei: "bn",
  bulgaria: "bg",
  burkina: "bf",
  burundi: "bi",
  cambodia: "kh",
  cameroon: "cm",
  canada: "ca",
  capeverde: "cv",
  centralafrica: "cf",
  chad: "td",
  chile: "cl",
  china: "cn",
  colombia: "co",
  comoros: "km",
  congo: "cg",
  costarica: "cr",
  croatia: "hr",
  cuba: "cu",
  cyprus: "cy",
  czechia: "cz",
  denmark: "dk",
  djibouti: "dj",
  dominica: "dm",
  dominicanrepublic: "do",
  ecuador: "ec",
  egypt: "eg",
  elsalvador: "sv",
  equatorialguinea: "gq",
  eritrea: "er",
  estonia: "ee",
  ethiopia: "et",
  fiji: "fj",
  finland: "fi",
  france: "fr",
  gabon: "ga",
  gambia: "gm",
  georgia: "ge",
  germany: "de",
  ghana: "gh",
  greece: "gr",
  grenada: "gd",
  guatemala: "gt",
  guinea: "gn",
  guineabissau: "gw",
  guyana: "gy",
  haiti: "ht",
  honduras: "hn",
  hongkong: "hk",
  hungary: "hu",
  iceland: "is",
  india: "in",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  israel: "il",
  italy: "it",
  ivorycoast: "ci",
  jamaica: "jm",
  japan: "jp",
  jordan: "jo",
  kazakhstan: "kz",
  kenya: "ke",
  kiribati: "ki",
  kuwait: "kw",
  kyrgyzstan: "kg",
  laos: "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  macao: "mo",
  madagascar: "mg",
  malawi: "mw",
  malaysia: "my",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  marshall: "mh",
  mauritania: "mr",
  mauritius: "mu",
  mexico: "mx",
  micronesia: "fm",
  moldova: "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "me",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  namibia: "na",
  nauru: "nr",
  nepal: "np",
  netherlands: "nl",
  newzealand: "nz",
  nicaragua: "ni",
  niger: "ne",
  nigeria: "ng",
  northkorea: "kp",
  northmacedonia: "mk",
  norway: "no",
  oman: "om",
  pakistan: "pk",
  palau: "pw",
  palestine: "ps",
  panama: "pa",
  papuanewguinea: "pg",
  paraguay: "py",
  peru: "pe",
  philippines: "ph",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  romania: "ro",
  russia: "ru",
  rwanda: "rw",
  saintkitts: "kn",
  saintlucia: "lc",
  saintvincentandgrenadines: "vc",
  samoa: "ws",
  sanmarino: "sm",
  saotomeandprincipe: "st",
  saudiarabia: "sa",
  senegal: "sn",
  serbia: "rs",
  seychelles: "sc",
  sierraleone: "sl",
  singapore: "sg",
  slovakia: "sk",
  slovenia: "si",
  solomonislands: "sb",
  somalia: "so",
  southafrica: "za",
  southkorea: "kr",
  southsudan: "ss",
  spain: "es",
  srilanka: "lk",
  sudan: "sd",
  suriname: "sr",
  sweden: "se",
  switzerland: "ch",
  syria: "sy",
  taiwan: "tw",
  tajikistan: "tj",
  tanzania: "tz",
  thailand: "th",
  timorleste: "tl",
  togo: "tg",
  tonga: "to",
  trinidadandtobago: "tt",
  tunisia: "tn",
  turkey: "tr",
  turkmenistan: "tm",
  tuvalu: "tv",
  uganda: "ug",
  ukraine: "ua",
  unitedarabemirates: "ae",
  unitedkingdom: "gb",
  unitedstates: "us",
  uruguay: "uy",
  uzbekistan: "uz",
  vanuatu: "vu",
  vatican: "va",
  venezuela: "ve",
  vietnam: "vn",
  yemen: "ye",
  zambia: "zm",
  zimbabwe: "zw",
  
  // Nationality-based keys (for matching nationality names)
  afghan: "af",
  albanian: "al",
  algerian: "dz",
  andorran: "ad",
  angolan: "ao",
  argentinian: "ar",
  armenian: "am",
  australian: "au",
  austrian: "at",
  azerbaijani: "az",
  bahamian: "bs",
  bahraini: "bh",
  bangladeshi: "bd",
  barbadian: "bb",
  belarusian: "by",
  belgian: "be",
  belizean: "bz",
  beninese: "bj",
  bhutanese: "bt",
  bolivian: "bo",
  bosnian: "ba",
  botswanan: "bw",
  brazilian: "br",
  bruneian: "bn",
  bulgarian: "bg",
  burkinabe: "bf",
  burundian: "bi",
  cambodian: "kh",
  cameroonian: "cm",
  canadian: "ca",
  capeverdean: "cv",
  centralafricanrepublic: "cf",
  chadian: "td",
  chilean: "cl",
  chinese: "cn",
  colombian: "co",
  comoran: "km",
  congolese: "cg",
  costarican: "cr",
  croatian: "hr",
  cuban: "cu",
  cypriot: "cy",
  czech: "cz",
  danish: "dk",
  djiboutian: "dj",
  dominican: "dm",
  dominicanrepublican: "do",
  ecuadorian: "ec",
  egyptian: "eg",
  salvadoran: "sv",
  equatorialguinean: "gq",
  eritrean: "er",
  estonian: "ee",
  ethiopian: "et",
  fijian: "fj",
  filipino: "ph",
  philippine: "ph",
  finnish: "fi",
  french: "fr",
  gabonese: "ga",
  gambian: "gm",
  georgian: "ge",
  german: "de",
  ghanaian: "gh",
  greek: "gr",
  grenadian: "gd",
  guatemalan: "gt",
  guinean: "gn",
  guineabissauan: "gw",
  guyanese: "gy",
  haitian: "ht",
  honduran: "hn",
  hungarian: "hu",
  icelandic: "is",
  indian: "in",
  indonesian: "id",
  iranian: "ir",
  iraqi: "iq",
  irish: "ie",
  israeli: "il",
  italian: "it",
  ivorian: "ci",
  jamaican: "jm",
  japanese: "jp",
  jordanian: "jo",
  kazakhstani: "kz",
  kenyan: "ke",
  kiribatian: "ki",
  northkorean: "kp",
  southkorean: "kr",
  kuwaiti: "kw",
  kyrgyzstani: "kg",
  laotian: "la",
  latvian: "lv",
  lebanese: "lb",
  lesothan: "ls",
  liberian: "lr",
  libyan: "ly",
  liechtensteiner: "li",
  lithuanian: "lt",
  luxembourgish: "lu",
  macedonian: "mk",
  malagasy: "mg",
  malawian: "mw",
  malaysian: "my",
  maldivian: "mv",
  malian: "ml",
  maltese: "mt",
  marshallese: "mh",
  mauritanian: "mr",
  mauritian: "mu",
  mexican: "mx",
  micronesian: "fm",
  moldovan: "md",
  monegasque: "mc",
  mongolian: "mn",
  montenegrin: "me",
  moroccan: "ma",
  mozambican: "mz",
  myanmar: "mm",
  namibian: "na",
  nauruan: "nr",
  nepalese: "np",
  dutch: "nl",
  newzealander: "nz",
  nicaraguan: "ni",
  nigerien: "ne",
  nigerian: "ng",
  norwegian: "no",
  omani: "om",
  pakistani: "pk",
  palauan: "pw",
  palestinian: "ps",
  panamanian: "pa",
  papuanewguinean: "pg",
  paraguayan: "py",
  peruvian: "pe",
  polish: "pl",
  portuguese: "pt",
  qatari: "qa",
  romanian: "ro",
  russian: "ru",
  rwandan: "rw",
  saintkittsandnevisian: "kn",
  saintlucian: "lc",
  vincentian: "vc",
  samoan: "ws",
  sammarinese: "sm",
  saotomean: "st",
  saudiarabian: "sa",
  senegalese: "sn",
  serbian: "rs",
  seychellois: "sc",
  sierraleone: "sl",
  sierraleonian: "sl",
  singaporean: "sg",
  slovak: "sk",
  slovenian: "si",
  solomonislander: "sb",
  somali: "so",
  southafrican: "za",
  spanish: "es",
  srilankan: "lk",
  sudanese: "sd",
  surinamese: "sr",
  swedish: "se",
  swiss: "ch",
  syrian: "sy",
  taiwanese: "tw",
  tajikistani: "tj",
  tanzanian: "tz",
  thai: "th",
  togolese: "tg",
  tongan: "to",
  trinidadandtobagonian: "tt",
  tunisian: "tn",
  turkish: "tr",
  turkmenistani: "tm",
  tuvaluan: "tv",
  ugandan: "ug",
  ukrainian: "ua",
  unitedarabemirati: "ae",
  british: "gb",
  american: "us",
  uruguayan: "uy",
  uzbekistani: "uz",
  vanuatuan: "vu",
  vatican: "va",
  venezuelan: "ve",
  vietnamese: "vn",
  yemeni: "ye",
  zambian: "zm",
  zimbabwean: "zw",
  easttimorese: "tl",
};